import { StyleSheet } from "react-native";

export const signinStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    paddingTop: 100,
    // backgroundColor: "grey",
  },
  inputs: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: 300,
    borderRadius: 50,
  },
  icon: {
    position: "absolute",
    width: "auto",
    height: "auto",
    zIndex: 1,
  },
  passwordBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  btnWrapper: {
    width: 200,
    marginTop: 10,
    backgroundColor: "#1A51BB",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  btnText: { color: "#fff", padding: 10 },
});

export const signupStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    paddingTop: 100,
    // backgroundColor: "grey",
  },
  inputs: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: 300,
    borderRadius: 50,
  },
  icon: {
    position: "absolute",
    width: "auto",
    height: "auto",
    zIndex: 1,
  },
  passwordBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  btnWrapper: {
    width: 200,
    marginTop: 10,
    backgroundColor: "#1A51BB",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  btnText: { color: "#fff", padding: 10 },
});

export const accountStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    rowGap: 25,
  },
  inputs: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "80%",
    borderRadius: 50,
  },
  btnWrapper: {
    width: 100,
    marginTop: 10,
    backgroundColor: "#1A51BB",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  btnText: { color: "#fff", padding: 10 },
  inputsDelete: {
    borderWidth: 1,
    borderColor: "#fda6a6",
    backgroundColor: "#fda6a6",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "80%",
    borderRadius: 50,
  },
  btnWrapperDelete: {
    width: 100,
    marginTop: 10,
    backgroundColor: "#bb1a1a",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  btnTextDelete: { color: "#fff", padding: 10 },
  F1: {
    padding: 20,
    borderRadius: 10,
    elevation: 40,
    backgroundColor: "#fff",
    width: "90%",
  },
  F2: {
    padding: 20,
    borderRadius: 10,
    elevation: 40,
    backgroundColor: "#fff",
    width: "90%",
  },
});

export const circleButtonStyle = StyleSheet.create({
  wrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    backgroundColor: "#152F64",
  },
  modalContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: {
    backgroundColor: "white",
    width: "60%",
    padding: 20,
    borderRadius: 10,
    elevation: 40,
  },
  btnWrapper: {
    width: 90,
    marginTop: 10,
    backgroundColor: "#1A51BB",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  btnText: { color: "#fff", padding: 10 },
  inputs: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: 200,
    borderRadius: 50,
  },
});

export const simpleListStyle = StyleSheet.create({
  container: {
    borderRadius: 20,
    elevation: 10,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignSelf: "center",
    width: "90%",
    padding: 20,
    backgroundColor: "#fff",
  },
  title: { fontWeight: "bold", fontSize: 24, textTransform: "uppercase" },
  modalContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: {
    backgroundColor: "white",
    width: "60%",
    padding: 20,
    borderRadius: 10,
    elevation: 40,
  },
  btnWrapper: {
    width: 90,
    marginTop: 10,
    backgroundColor: "#1A51BB",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  wrapper1: { position: "absolute", top: 20, right: 100 },
  wrapper2: { position: "absolute", top: 20, right: 30 },
  btnText: { color: "#fff", padding: 10 },
  inputs: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: 200,
    borderRadius: 50,
  },
});

export const circleButtonStyleV2 = StyleSheet.create({
  wrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    backgroundColor: "#152F64",
  },
  modalContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: {
    backgroundColor: "white",
    width: "60%",
    padding: 20,
    borderRadius: 10,
    elevation: 40,
  },
  btnWrapper: {
    width: 90,
    marginTop: 10,
    backgroundColor: "#1A51BB",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  btnText: { color: "#fff", padding: 10 },
  inputs: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "90%",
    borderRadius: 50,
    elevation: 20,
  },
  inputsContent: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "90%",
    height: "70%",
    textAlignVertical: "top",
    borderRadius: 10,
    elevation: 20,
  },
  picker: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "90%",
    borderRadius: 10,
    elevation: 20,
  },
});

export const complexListStyle = StyleSheet.create({
  container: {
    borderRadius: 20,
    elevation: 10,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignSelf: "center",
    width: "90%",
    padding: 20,
    backgroundColor: "#fff",
  },
  title: { fontWeight: "bold", fontSize: 24, textTransform: "uppercase" },
  col: {
    fontWeight: "bold",
    fontSize: 24,
    textTransform: "uppercase",
    color: "#1A51BB",
  },
  modalContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: {
    backgroundColor: "white",
    width: "60%",
    padding: 20,
    borderRadius: 10,
    elevation: 40,
  },
  btnWrapper: {
    width: 90,
    marginTop: 10,
    backgroundColor: "#1A51BB",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  wrapper1: { position: "absolute", top: 20, right: 100 },
  wrapper2: { position: "absolute", top: 20, right: 30 },
  btnText: { color: "#fff", padding: 10 },
  inputs: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "90%",
    borderRadius: 50,
    elevation: 20,
  },
  inputsContent: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "90%",
    height: "70%",
    textAlignVertical: "top",
    borderRadius: 10,
    elevation: 20,
  },
  picker: {
    borderWidth: 1,
    borderColor: "#A6C4FD",
    backgroundColor: "#A6C4FD",
    color: "#092C70",
    padding: 8,
    margin: 10,
    width: "90%",
    borderRadius: 10,
    elevation: 20,
  },
});
